# Generate mobile test-resource deploy MSBuild project from SolLib.Tests/src/Resources.
# Renames each fixture to its normalized RC symbol name (PathToResourceName) for flat
# deployment under Documents/SolLib/ on device.
#
# Usage:
#   .\sync-mobile-test-resources.ps1
#   .\sync-mobile-test-resources.ps1 -DeployProjName SolLib.Tests.Mobile.TestData.deployproj -AppDeployFolderName SolLib.Tests.Mobile
#
# Re-run when files under SolLib.Tests/src/Resources change (or AppDeployFolderName changes),
# then rebuild the mobile test host.
#
# Library resources (BIP39 wordlists, KD table) are NOT included.

param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$DeployProjName = "SolLib.Tests.Mobile.TestData.deployproj",
    [string]$AppDeployFolderName = "SolLib.Tests.Mobile"
)

$DelphiTestsDir = Join-Path $RepoRoot "SolLib.Tests\Delphi.Tests"
$ResourcesDir = Join-Path $RepoRoot "SolLib.Tests\src\Resources"
$RcPath = Join-Path $ResourcesDir "TestResources.rc"
$OutPath = Join-Path $DelphiTestsDir $DeployProjName

if (-not (Test-Path $ResourcesDir)) {
    Write-Error "Resources directory not found: $ResourcesDir"
    exit 1
}

function Escape-Xml([string]$Text) {
    return $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

# Mirror TestResourceLoader.PathToResourceName in Pascal (keep in sync).
function ConvertTo-ResourceName([string]$RelativePath) {
    $result = $RelativePath -replace '\\', '/'
    $result = $result -replace '/', '_'
    $result = $result -ireplace '\.json', '_JSON'
    $result = $result -ireplace '\.txt', '_TXT'
    $result = $result -replace '\.', '_'
    $result = $result -replace '-', '_'
    return $result.ToUpper()
}

function New-DeployFileBlock {
    param(
        [string]$IncludePath,
        [string]$RemoteDir,
        [string]$RemoteName
    )
    $inc = Escape-Xml $IncludePath
    $dir = Escape-Xml $RemoteDir
    $name = Escape-Xml $RemoteName
    return @"
        <DeployFile Include="$inc">
            <RemoteDir>$dir</RemoteDir>
            <RemoteName>$name</RemoteName>
            <DeployClass>File</DeployClass>
            <Operation>0</Operation>
            <LocalCommand/>
            <RemoteCommand/>
            <Overwrite>True</Overwrite>
        </DeployFile>
"@
}

$AndroidRemoteDir = "$AppDeployFolderName\assets\internal\SolLib\"
$IosRemoteDir = "StartUpDocuments\SolLib\"

$AndroidBlocks = New-Object System.Collections.Generic.List[string]
$IosBlocks = New-Object System.Collections.Generic.List[string]
$NameMap = @{}

Get-ChildItem -Path $ResourcesDir -Recurse -File -Include *.json, *.txt | ForEach-Object {
    $rel = $_.FullName.Substring($ResourcesDir.Length).TrimStart('\', '/')
    $resourceName = ConvertTo-ResourceName $rel
    $include = "..\src\Resources\$($rel -replace '/', '\')"
    $remoteName = $resourceName

    if ($NameMap.ContainsKey($remoteName)) {
        Write-Warning "Duplicate normalized name '$remoteName' for '$rel' and '$($NameMap[$remoteName])'"
    }
    else {
        $NameMap[$remoteName] = $rel
    }

    $AndroidBlocks.Add((New-DeployFileBlock -IncludePath $include -RemoteDir $AndroidRemoteDir -RemoteName $remoteName))
    $IosBlocks.Add((New-DeployFileBlock -IncludePath $include -RemoteDir $IosRemoteDir -RemoteName $remoteName))
}

# Optional cross-check against TestResources.rc (first 5 mismatches only).
if (Test-Path $RcPath) {
    $rcContent = Get-Content $RcPath -Raw
    $mismatchCount = 0
    foreach ($entry in $NameMap.GetEnumerator()) {
        $expectedPattern = "$($entry.Key)\s+RCDATA"
        if ($rcContent -notmatch $expectedPattern) {
            if ($mismatchCount -lt 5) {
                Write-Warning "TestResources.rc may be missing symbol: $($entry.Key) (from $($entry.Value))"
            }
            $mismatchCount++
        }
    }
    if ($mismatchCount -gt 0) {
        Write-Warning "TestResources.rc cross-check: $mismatchCount symbol(s) not found in .rc (regenerate .rc if fixtures changed)."
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">')
[void]$sb.AppendLine('    <!-- Generated by scripts/sync-mobile-test-resources.ps1 - do not edit by hand -->')
[void]$sb.AppendLine("    <!-- AppDeployFolderName=$AppDeployFolderName DeployProjName=$DeployProjName -->")
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''Android64''">')
foreach ($b in $AndroidBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''iOSDevice64''">')
foreach ($b in $IosBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''iOSSimARM64''">')
foreach ($b in $IosBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('</Project>')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $($AndroidBlocks.Count) test resource deploy entries to $OutPath (AppDeployFolderName=$AppDeployFolderName)"
