program SolLib.Examples;

{$STRONGLINKTYPES ON}

{$APPTYPE CONSOLE}

{$R *.res}

uses
  SysUtils,
  SlpTokenModel in '..\..\SolLib\src\Token\SlpTokenModel.pas',
  SlpTokenMintResolver in '..\..\SolLib\src\Token\SlpTokenMintResolver.pas',
  SlpTokenDomain in '..\..\SolLib\src\Token\SlpTokenDomain.pas',
  SlpTokenWalletRpcProxy in '..\..\SolLib\src\Token\SlpTokenWalletRpcProxy.pas',
  SlpWellKnownTokens in '..\..\SolLib\src\Token\SlpWellKnownTokens.pas',
  SlpJsonHelpers in '..\..\SolLib\src\Helpers\SlpJsonHelpers.pas',
  SlpValueHelpers in '..\..\SolLib\src\Helpers\SlpValueHelpers.pas',
  SlpBaseJsonConverter in '..\..\SolLib\src\JsonConverters\SlpBaseJsonConverter.pas',
  SlpAccountDataConverter in '..\..\SolLib\src\JsonConverters\SlpAccountDataConverter.pas',
  SlpObjectOrStringArrayConverter in '..\..\SolLib\src\JsonConverters\SlpObjectOrStringArrayConverter.pas',
  SlpEncodingConverter in '..\..\SolLib\src\JsonConverters\SlpEncodingConverter.pas',
  SlpJsonListConverter in '..\..\SolLib\src\JsonConverters\SlpJsonListConverter.pas',
  SlpBaseJsonBatchConverter in '..\..\SolLib\src\JsonConverters\SlpBaseJsonBatchConverter.pas',
  SlpJsonRpcBatchRequestConverter in '..\..\SolLib\src\JsonConverters\SlpJsonRpcBatchRequestConverter.pas',
  SlpJsonRpcBatchResponseConverter in '..\..\SolLib\src\JsonConverters\SlpJsonRpcBatchResponseConverter.pas',
  SlpJsonRpcBatchResponseItemResultConverter in '..\..\SolLib\src\JsonConverters\SlpJsonRpcBatchResponseItemResultConverter.pas',
  SlpJsonRpcRequestParamsConverter in '..\..\SolLib\src\JsonConverters\SlpJsonRpcRequestParamsConverter.pas',
  SlpJsonStringEnumConverter in '..\..\SolLib\src\JsonConverters\SlpJsonStringEnumConverter.pas',
  SlpNullableConverter in '..\..\SolLib\src\JsonConverters\SlpNullableConverter.pas',
  SlpRpcErrorResponseConverter in '..\..\SolLib\src\JsonConverters\SlpRpcErrorResponseConverter.pas',
  SlpTokenListItemExtensionsConverter in '..\..\SolLib\src\JsonConverters\SlpTokenListItemExtensionsConverter.pas',
  SlpTransactionErrorJsonConverter in '..\..\SolLib\src\JsonConverters\SlpTransactionErrorJsonConverter.pas',
  SlpTransactionMetaInfoVersionConverter in '..\..\SolLib\src\JsonConverters\SlpTransactionMetaInfoVersionConverter.pas',
  SlpJsonClampNumberConverter in '..\..\SolLib\src\JsonConverters\SlpJsonClampNumberConverter.pas',
  SlpJsonKeyStoreSerializer in '..\..\SolLib\src\KeyStore\SlpJsonKeyStoreSerializer.pas',
  SlpKeyStoreCrypto in '..\..\SolLib\src\KeyStore\SlpKeyStoreCrypto.pas',
  SlpKeyStoreEnum in '..\..\SolLib\src\KeyStore\SlpKeyStoreEnum.pas',
  SlpKeyStoreKdfChecker in '..\..\SolLib\src\KeyStore\SlpKeyStoreKdfChecker.pas',
  SlpKeyStoreModel in '..\..\SolLib\src\KeyStore\SlpKeyStoreModel.pas',
  SlpKeyStoreService in '..\..\SolLib\src\KeyStore\SlpKeyStoreService.pas',
  SlpSecretKeyStoreService in '..\..\SolLib\src\KeyStore\SlpSecretKeyStoreService.pas',
  SlpSolanaKeyStoreService in '..\..\SolLib\src\KeyStore\SlpSolanaKeyStoreService.pas',
  SlpBitWriter in '..\..\SolLib\src\Misc\SlpBitWriter.pas',
  SlpDataEncoderProviders in '..\..\SolLib\src\Misc\Encoder\SlpDataEncoderProviders.pas',
  SlpDefaultDataEncoderProviders in '..\..\SolLib\src\Misc\Encoder\SlpDefaultDataEncoderProviders.pas',
  SlpJsonKit in '..\..\SolLib\src\Misc\SlpJsonKit.pas',
  SlpNullable in '..\..\SolLib\src\Misc\SlpNullable.pas',
  SlpSolLibExceptions in '..\..\SolLib\src\Misc\SlpSolLibExceptions.pas',
  SlpStringTransformer in '..\..\SolLib\src\Misc\SlpStringTransformer.pas',
  SlpTimeTicker in '..\..\SolLib\src\Misc\SlpTimeTicker.pas',
  SlpMulticast in '..\..\SolLib\src\Misc\SlpMulticast.pas',
  SlpResourceLoader in '..\..\SolLib\src\Misc\SlpResourceLoader.pas',
  SlpKdTable in '..\..\SolLib\src\Misc\Normalization\SlpKdTable.pas',
  SlpArrayUtilities in '..\..\SolLib\src\Utilities\SlpArrayUtilities.pas',
  SlpCryptoUtilities in '..\..\SolLib\src\Utilities\SlpCryptoUtilities.pas',
  SlpDataEncoderUtilities in '..\..\SolLib\src\Utilities\SlpDataEncoderUtilities.pas',
  SlpListUtilities in '..\..\SolLib\src\Utilities\SlpListUtilities.pas',
  SlpValueUtilities in '..\..\SolLib\src\Utilities\SlpValueUtilities.pas',
  SlpIOUtilities in '..\..\SolLib\src\Utilities\SlpIOUtilities.pas',
  SlpMathUtilities in '..\..\SolLib\src\Utilities\SlpMathUtilities.pas',
  SlpEnumUtilities in '..\..\SolLib\src\Utilities\SlpEnumUtilities.pas',
  SlpAccount in '..\..\SolLib\src\Wallet\SlpAccount.pas',
  SlpEd25519Bip32 in '..\..\SolLib\src\Wallet\SlpEd25519Bip32.pas',
  SlpPrivateKey in '..\..\SolLib\src\Wallet\SlpPrivateKey.pas',
  SlpPublicKey in '..\..\SolLib\src\Wallet\SlpPublicKey.pas',
  SlpWallet in '..\..\SolLib\src\Wallet\SlpWallet.pas',
  SlpWalletEnum in '..\..\SolLib\src\Wallet\SlpWalletEnum.pas',
  SlpHardcodedWordListSource in '..\..\SolLib\src\Wallet\Bip39\SlpHardcodedWordListSource.pas',
  SlpMnemonic in '..\..\SolLib\src\Wallet\Bip39\SlpMnemonic.pas',
  SlpWordList in '..\..\SolLib\src\Wallet\Bip39\SlpWordList.pas',
  SlpAccountDomain in '..\..\SolLib\src\Rpc\SlpAccountDomain.pas',
  SlpClientFactory in '..\..\SolLib\src\Rpc\SlpClientFactory.pas',
  SlpConnectionStatistics in '..\..\SolLib\src\Rpc\SlpConnectionStatistics.pas',
  SlpIdGenerator in '..\..\SolLib\src\Rpc\SlpIdGenerator.pas',
  SlpMessageBuilder in '..\..\SolLib\src\Rpc\SlpMessageBuilder.pas',
  SlpMessageDomain in '..\..\SolLib\src\Rpc\SlpMessageDomain.pas',
  SlpRateLimiter in '..\..\SolLib\src\Rpc\SlpRateLimiter.pas',
  SlpRpcEnum in '..\..\SolLib\src\Rpc\SlpRpcEnum.pas',
  SlpRpcMessage in '..\..\SolLib\src\Rpc\SlpRpcMessage.pas',
  SlpRpcModel in '..\..\SolLib\src\Rpc\SlpRpcModel.pas',
  SlpShortVectorEncoding in '..\..\SolLib\src\Rpc\SlpShortVectorEncoding.pas',
  SlpRequestResult in '..\..\SolLib\src\Rpc\Http\SlpRequestResult.pas',
  SlpSolanaRpcBatchComposer in '..\..\SolLib\src\Rpc\Http\SlpSolanaRpcBatchComposer.pas',
  SlpSolanaRpcBatchWithCallbacks in '..\..\SolLib\src\Rpc\Http\SlpSolanaRpcBatchWithCallbacks.pas',
  SlpJsonRpcClient in '..\..\SolLib\src\Rpc\Http\SlpJsonRpcClient.pas',
  SlpSolanaRpcClient in '..\..\SolLib\src\Rpc\Http\SlpSolanaRpcClient.pas',
  SlpSubscriptionEvent in '..\..\SolLib\src\Rpc\Sockets\SlpSubscriptionEvent.pas',
  SlpStreamingRpcClient in '..\..\SolLib\src\Rpc\Sockets\SlpStreamingRpcClient.pas',
  SlpSolanaStreamingRpcClient in '..\..\SolLib\src\Rpc\Sockets\SlpSolanaStreamingRpcClient.pas',
  SlpTransactionBuilder in '..\..\SolLib\src\Rpc\SlpTransactionBuilder.pas',
  SlpTransactionInstruction in '..\..\SolLib\src\Rpc\SlpTransactionInstruction.pas',
  SlpTransactionInstructionFactory in '..\..\SolLib\src\Rpc\SlpTransactionInstructionFactory.pas',
  SlpTransactionDomain in '..\..\SolLib\src\Rpc\SlpTransactionDomain.pas',
  SlpConfigObject in '..\..\SolLib\src\Rpc\SlpConfigObject.pas',
  SlpComputeBudgetEstimator in '..\..\SolLib\src\Rpc\SlpComputeBudgetEstimator.pas',
  SlpHttpApiClient in '..\..\SolLib\src\Misc\Http\SlpHttpApiClient.pas',
  SlpHttpApiResponse in '..\..\SolLib\src\Misc\Http\SlpHttpApiResponse.pas',
  SlpWebSocketClientBase in '..\..\SolLib\src\Misc\Sockets\SlpWebSocketClientBase.pas',
  SlpWebSocketApiClient in '..\..\SolLib\src\Misc\Sockets\SlpWebSocketApiClient.pas',
  SlpSolLibTypes in '..\..\SolLib\src\Misc\SlpSolLibTypes.pas',
  SlpJsonConverterFactory in '..\..\SolLib\src\JsonConverters\SlpJsonConverterFactory.pas',
  SlpCryptoProviders in '..\..\SolLib\src\Misc\Crypto\SlpCryptoProviders.pas',
  SlpDefaultCryptoProviders in '..\..\SolLib\src\Misc\Crypto\SlpDefaultCryptoProviders.pas',
  SlpHttpClientBase in '..\..\SolLib\src\Misc\Http\SlpHttpClientBase.pas',
  SlpDelphiHttpClient in '..\..\SolLib\src\Misc\Http\SlpDelphiHttpClient.pas',
  SlpComparerFactory in '..\..\SolLib\src\Misc\SlpComparerFactory.pas',
  SlpBinaryPrimitives in '..\..\SolLib\src\Misc\SlpBinaryPrimitives.pas',
  SlpLogger in '..\..\SolLib\src\Misc\Logger\SlpLogger.pas',
  SlpSolConverter in '..\..\SolLib\src\Token\SlpSolConverter.pas',
  SlpTokenWallet in '..\..\SolLib\src\Token\SlpTokenWallet.pas',
  SlpResultWrapper in '..\..\SolLib\src\Programs\Abstract\SlpResultWrapper.pas',
  SlpBaseClient in '..\..\SolLib\src\Programs\Abstract\SlpBaseClient.pas',
  SlpBaseProgram in '..\..\SolLib\src\Programs\Abstract\SlpBaseProgram.pas',
  SlpFlag in '..\..\SolLib\src\Programs\Abstract\SlpFlag.pas',
  SlpDecodedInstruction in '..\..\SolLib\src\Programs\Models\SlpDecodedInstruction.pas',
  SlpNonceAccount in '..\..\SolLib\src\Programs\Models\SlpNonceAccount.pas',
  SlpTokenProgramModel in '..\..\SolLib\src\Programs\Models\SlpTokenProgramModel.pas',
  SlpTokenSwapModel in '..\..\SolLib\src\Programs\Models\SlpTokenSwapModel.pas',
  SlpSerialization in '..\..\SolLib\src\Programs\Utils\SlpSerialization.pas',
  SlpDeserialization in '..\..\SolLib\src\Programs\Utils\SlpDeserialization.pas',
  SlpInstructionDecoder in '..\..\SolLib\src\Programs\Utils\SlpInstructionDecoder.pas',
  SlpSysVars in '..\..\SolLib\src\Programs\SlpSysVars.pas',
  SlpTokenProgram in '..\..\SolLib\src\Programs\SlpTokenProgram.pas',
  SlpSystemProgram in '..\..\SolLib\src\Programs\SlpSystemProgram.pas',
  SlpToken2022Program in '..\..\SolLib\src\Programs\SlpToken2022Program.pas',
  SlpTokenSwapProgram in '..\..\SolLib\src\Programs\SlpTokenSwapProgram.pas',
  SlpAssociatedTokenAccountProgram in '..\..\SolLib\src\Programs\SlpAssociatedTokenAccountProgram.pas',
  SlpMemoProgram in '..\..\SolLib\src\Programs\SlpMemoProgram.pas',
  SlpComputeBudgetProgram in '..\..\SolLib\src\Programs\SlpComputeBudgetProgram.pas',
  SlpSharedMemoryProgram in '..\..\SolLib\src\Programs\SlpSharedMemoryProgram.pas',
  SlpAddressLookupTableProgram in '..\..\SolLib\src\Programs\SlpAddressLookupTableProgram.pas',
  SlpBPFLoaderProgram in '..\..\SolLib\src\Programs\SlpBPFLoaderProgram.pas',
  ExampleExplorer in '..\src\ExampleExplorer.pas',
  TokenMintHelper in '..\src\TokenMintHelper.pas',
  ConsoleLogger in '..\src\ConsoleLogger.pas',
  ExampleBase in '..\src\ExampleBase.pas',
  InstructionDecoderExample in '..\src\InstructionDecoderExample.pas',
  GetTokenAccountsByOwnerExample in '..\src\GetTokenAccountsByOwnerExample.pas',
  SolanaKeygenWalletExample in '..\src\SolanaKeygenWalletExample.pas',
  SolletKeyGenerationExample in '..\src\SolletKeyGenerationExample.pas',
  SolletKeygenKeystoreExample in '..\src\SolletKeygenKeystoreExample.pas',
  TokenWalletExample in '..\src\TokenWalletExample.pas',
  TransactionDecodingExample in '..\src\TransactionDecodingExample.pas',
  TransactionExample in '..\src\TransactionExample.pas',
  TransactionExtendedExample in '..\src\TransactionExtendedExample.pas',
  AssociatedTokenAccountsExample in '..\src\AssociatedTokenAccountsExample.pas',
  MultisigExample in '..\src\MultisigExample.pas',
  TokenSwapExample in '..\src\TokenSwapExample.pas';

begin
  TExampleLogger.SetDefaultLogger((TConsoleLoggerFactory.Create(TLogLevel.Info) as ILoggerFactory).CreateLogger('Examples'));
  try
    TExampleExplorer.Execute;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
